export const regions = [
    {
        name: 'kiev',
        title: 'Київська область',
        lat: 50.27,
        lng: 30.45,
    },
    {
        name: 'zhytomyr',
        title: 'Житомирська область',
        lat: 50.05,
        lng: 28.63,
    },
    {
        name: 'chernivtsi',
        title: 'Чернівецька область',
        lat: 48.27,
        lng: 25.93,
    },
    {
        name: 'donetsk',
        title: 'Донецька область',
        lat: 47.85,
        lng: 37.73,
    },
    {
        name: 'dnipropetrovsk',
        title: 'Дніпропетровська область',
        lat: 48.30,
        lng: 35.05,
    },
    {
        name: 'ivanofrankivsk',
        title: 'Івано-Франківська область',
        lat: 48.87,
        lng: 24.66,
    },
    {
        name: 'lviv',
        title: 'Львівська область',
        lat: 49.78,
        lng: 24.02,
    },
    {
        name: 'ternopil',
        title: 'Тернопільска область',
        lat: 49.54,
        lng: 25.60,
    },
    {
        name: 'cherkasy',
        title: 'Черкаська область',
        lat: 49.27,
        lng: 32.00,
    },
    {
        name: 'odessa',
        title: 'Одеська область',
        lat: 46.27,
        lng: 30.65,
    },
    {
        name: 'luhansk',
        title: 'Луганська область',
        lat: 48.35,
        lng: 39.15,
    },
    {
        name: 'zaporizhzhya',
        title: 'Запорізька область',
        lat: 47.68,
        lng: 35.15,
    },
    {
        name: 'volyn',
        title: 'Волинська область',
        lat: 50.75,
        lng: 25.15,
    },
    {
        name: 'crimea',
        title: 'Окупований Крим',
        lat: 44.58,
        lng: 34.06,
    },
    {
        name: 'sumy',
        title: 'Сумська область',
        lat: 50.53,
        lng: 34.45,
    },
    {
        name: 'vinnytsya',
        title: 'Віннитська область',
        lat: 49.14,
        lng: 28.30,
    },
    {
        name: 'transcarpathia',
        title: 'Закарпатська область',
        lat: 48.38,
        lng: 22.60,
    },
    {
        name: 'mykolayiv',
        title: 'Миколаївська область',
        lat: 46.92,
        lng: 32.00,
    },
    {
        name: 'rivne',
        title: 'Рівенська область',
        lat: 50.55,
        lng: 26.20,
    },
    {
        name: 'kherson',
        title: 'Херсонська область',
        lat: 46.60,
        lng: 32.60,
    },
    {
        name: 'chernihiv',
        title: 'Чернігівська область',
        lat: 51.29,
        lng: 31.18,
    },
    {
        name: 'khmelnytskyy',
        title: 'Хмельницька область',
        lat: 49.24,
        lng: 27.00,
    },
    {
        name: 'poltava',
        title: 'Полтавська область',
        lat: 49.36,
        lng: 34.34,
    },
    {
        name: 'kirovohrad',
        title: 'Кіровоградська область',
        lat: 48.30,
        lng: 32.15,
    },
    {
        name: 'kharkiv',
        title: 'Харківська область',
        lat: 49.90,
        lng: 36.20,
    },
];
