export const regions = [
    {
        name: 'kiev',
        title: 'Київська область',
        lat: 50.27,
        lng: 30.45,
    },
    {
        name: 'zhytomyr',
        title: 'Житомирська область',
        lat: 50.05,
        lng: 28.63,
    },
    {
        name: 'chernivtsi',
        title: 'Чернівецька область',
        lat: 48.12,
        lng: 26.05,
    },
    {
        name: 'donetsk',
        title: 'Донецька область',
        lat: 47.85,
        lng: 37.73,
    },
    {
        name: 'dnipropetrovsk',
        title: 'Дніпропетровська область',
        lat: 48.30,
        lng: 35.05,
    },
    {
        name: 'ivanofrankivsk',
        title: 'Івано-Франковська область',
        lat: 48.76,
        lng: 24.55,
    },
    {
        name: 'lviv',
        title: 'Львівська область',
        lat: 49.71,
        lng: 24.02,
    },
    {
        name: 'ternopil',
        title: 'Тернопільска область',
        lat: 49.34,
        lng: 25.60,
    },
    {
        name: 'cherkasy',
        title: 'Черкаська область',
        lat: 49.27,
        lng: 32.00,
    },
    {
        name: 'odessa',
        title: 'Одеська область',
        lat: 46.27,
        lng: 30.65,
    },
    {
        name: 'luhansk',
        title: 'Луганська область',
        lat: 48.35,
        lng: 39.15,
    },
    {
        name: 'zaporizhzhya',
        title: 'Запорізька область',
        lat: 47.68,
        lng: 35.15,
    },
    {
        name: 'volyn',
        title: 'Волинська область',
        lat: 50.75,
        lng: 25.15,
    },
    {
        name: 'crimea',
        title: 'Окупований Крим',
        lat: 44.58,
        lng: 34.06,
    },
    {
        name: 'sumy',
        title: 'Сумська область',
        lat: 50.53,
        lng: 34.45,
    },
];
